# Generated by Django 3.0.8 on 2020-07-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(editable=False)),
                ('ts', models.CharField(editable=False, max_length=255)),
                ('latlong', models.CharField(editable=False, max_length=255)),
                ('noun', models.CharField(editable=False, max_length=10)),
                ('verb', models.CharField(editable=False, max_length=10)),
                ('timespent', models.IntegerField(editable=False, null=True)),
                ('properties', models.TextField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventRules',
            fields=[
                ('event_rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(editable=False, max_length=255, unique=True)),
                ('rule_description', models.TextField(editable=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
